# COMMANDER V1

# Commander Ranks (Basic Usage)

# Gets public profile if enabled
GET https://www.edsm.net/api-commander-v1/get-ranks?commanderName={{commanderName}}

###

GET https://www.edsm.net/api-commander-v1/get-ranks
    ?commanderName={{commanderName}}
    &apiKey={{apiKey}}

###



# Commander Credits (Basic Usage)

GET https://www.edsm.net/api-commander-v1/get-credits
    ?commanderName={{commanderName}}
    &apiKey={{apiKey}}

###


# Commander Credits (Using a period to show credits within the period)

# Valid values for period are 7DAY, 1MONTH, 3MONTH, 6MONTH 
GET https://www.edsm.net/api-commander-v1/get-credits
    ?commanderName={{commanderName}}
    &apiKey={{apiKey}}
    &period=7DAYS

###



# Commander Materials/Cargo/Data (Basic Usage)

# Gets public profile if enabled
GET https://www.edsm.net/api-commander-v1/get-materials?commanderName={{commanderName}}

###


GET https://www.edsm.net/api-commander-v1/get-materials
    ?commanderName={{commanderName}}
    &apiKey={{apiKey}}

###


# Commander Materials/Cargo/Data (Using a material type filter)

# Valid values for type are materials, cargo, data 
GET https://www.edsm.net/api-commander-v1/get-materials
    ?commanderName={{commanderName}}
    &apiKey={{apiKey}}
    &type=cargo

###