# SYSTEM V1

# System Bodies Info (Basic Usage)

https://www.edsm.net/api-system-v1/bodies
    ?systemName=Sol

###


# System Bodies Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/bodies?
    ?systemName=Sol
    &systemId=27

###


# System Estimated Scan Value (Basic Usage)

https://www.edsm.net/api-system-v1/estimated-value
    ?systemName=Sol

###


# System Estimated Scan Value (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/estimated-value
    ?systemName=Sol
    &systemId=27

###



# System Stations Info (Basic Usage)

https://www.edsm.net/api-system-v1/stations
    ?systemName=Sol

### 


# System Stations Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/stations
    ?systemName=Sol
    &systemId=27

###


# Station Market Info (Basic Usage)

https://www.edsm.net/api-system-v1/stations/market
    ?systemName=Sol
    &marketId=128016384
    

###

https://www.edsm.net/api-system-v1/stations/market
    ?systemName=Sol
    &stationName=Daedalus

###


# Station Market Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/stations/market
    ?systemName=Sol
    &marketId=128016384
    &systemId=27

###



# Station Shipyard Info (Basic Usage)

https://www.edsm.net/api-system-v1/stations/shipyard
    ?systemName=Sol
    &marketId=128016384

###

https://www.edsm.net/api-system-v1/stations/shipyard
    ?systemName=Sol
    &stationName=Daedalus

###


# Station Shipyard Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/stations/shipyard
    ?systemName=Sol
    &marketId=128016384
    &systemId=27

###



# Station Outfitting Info (Basic Usage)

https://www.edsm.net/api-system-v1/stations/outfitting
    ?systemName=Sol
    &marketId=128016384

###

https://www.edsm.net/api-system-v1/stations/shipyard
    ?systemName=Sol
    &stationName=Daedalus


# Station Outfitting Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/stations/outfitting
    ?systemName=Sol
    &marketId=128016384
    &systemId=27

###



# System Factions Info (Basic Usage)

https://www.edsm.net/api-system-v1/factions
    ?systemName=Sol

###


# System Factions Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/factions
    ?systemName=Sol
    &systemId=27

###


# System Factions Info (System history enabled)

https://www.edsm.net/api-system-v1/factions
    ?systemName=Sol
    &showHistory=1

###


 
# System Traffic Info (Basic Usage)

https://www.edsm.net/api-system-v1/traffic
    ?systemName=Sol

###


# System Traffic Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/traffic
    ?systemName=Sol
    &systemId=27

###



# System Deaths Info (Basic Usage)

https://www.edsm.net/api-system-v1/deaths
    ?systemName=Sol

###



# System Deaths Info (Using a internal EDSM id)

https://www.edsm.net/api-system-v1/deaths
    ?systemName=Sol
    &systemId=27

### 